disableKinds = ["taxonomy", "taxonomy"]
enableEmoji = true


baseURL = "/"
languageCode = "en-us"
title = "Life in Weeks"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

[params]
  author = "haibin"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
